### ISSUE TITLE
data frame test fails

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/sos-julia#5]
```
ERROR: testGetPythonDataFrameFromJulia (__main__.TestJuliaKernel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_Julia_kernel.py", line 53, in testGetPythonDataFrameFromJulia
    execute(kc=kc, code="%get df")
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/ipykernel/tests/utils.py", line 66, in execute
    reply = kc.get_shell_msg(timeout=TIMEOUT)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty
```

<img width="921" alt="screen shot 2018-07-24 at 6 09 52 pm" src="https://user-images.githubusercontent.com/26916551/43170836-c7a86fa8-8f6c-11e8-8da9-253e16a14f78.png">

**Comment by HenryLeongStat** [comment]
Clean up the code a little bit. Seems like https://github.com/vatlab/sos-julia/commit/88d3284e9c3c6abee05b8a9026d21a691e8faf9e fixed the test somehow... 😕
